Revert "autoninja: set RBE_remote_disabled when offline even with siso"
This reverts commit 7a0dbd20744917e3124a36276ef039848c4229ed.

Reason for revert: By de-indenting the code, it is ran even when use_siso is undefined, resulting in the following error

```
autoninja -C out/gn chrome
Traceback (most recent call last):
  File "/usr/local/google/home/msta/programs/depot_tools/autoninja.py", line 520, in main
    exit_code = _main_inner(input_args, build_id, should_collect_logs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/msta/programs/depot_tools/autoninja.py", line 339, in _main_inner
    if use_siso:
       ^^^^^^^^
UnboundLocalError: cannot access local variable 'use_siso' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/google/home/msta/programs/depot_tools/autoninja.py", line 531, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/local/google/home/msta/programs/depot_tools/autoninja.py", line 526, in main
    _upload_ninjalog(input_args, exit_code, elapsed)
                                 ^^^^^^^^^
UnboundLocalError: cannot access local variable 'exit_code' where it is not associated with a value
```

Original change's description:
> autoninja: set RBE_remote_disabled when offline even with siso
>
> Bug: 396724264
> Change-Id: Id92e8d532e571420ff64be3da207ffd51fd282e9
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/tools/depot_tools/+/6272278
> Commit-Queue: Junji Watanabe <jwata@google.com>
> Auto-Submit: Fumitoshi Ukai <ukai@google.com>
> Reviewed-by: Junji Watanabe <jwata@google.com>

Bug: 396724264
Change-Id: I19697d92253d1a541e92253d581b0854e4a0a543
No-Presubmit: true
No-Tree-Checks: true
No-Try: true